name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 1.25

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18'

      - name: Scratch init 
        run: |
          go tool \
            github.com/go-task/task/v3/cmd/task \
              --silent \
              scratch:init

      - name: Create build 
        run: |
          go tool \
            github.com/go-task/task/v3/cmd/task \
              --silent \
             app:build

      - name: Create build 
        run: |
          go tool \
            github.com/go-task/task/v3/cmd/task \
              --silent \
             app:zip
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: scratch-arduino-app-zip
          path: |
            build/*.zip
          if-no-files-found: error